# This is based (somewhat) on a file generated by debian, but it works very nicely on everything else

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# And the prize for the most unintuative .bashrc file goes to: Debian!

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
#if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
 #   debian_chroot=$(cat /etc/debian_chroot)
#fi

# Sets window title to user@hostname: working direcotru
PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'

#bold=$(tput bold)
# C'mon Debian it isn't that hard
#PS1='\[\033[0;37m\][\033[01;34m\]\u\[\033[1;37m\]@\[\033[1;34m\]\h\[\033[37m\]:\[\033[34m\]\w\[\033[0;37m\]]$ '
#export PS1="[\[\e[1;34m\]\u\[\e[m\]@\[\e[1;34m\]\h\[\e[m\]:\[\e[1;34m\]\W\[\e[1;m\]]\[\e[1;37m\]\\$\[\e[m\] "
export PS1="\[\e[1;37m\][\[\e[1;m\]\[\e[1;34m\]\u\[\e[1;m\]\[\e[1;37m\]@\[\e[1;m\]\[\e[1;34m\]\h\[\e[1;m\]\[\e[1;37m\]:\[\e[m\]\[\e[1;34m\]\w\[\e[1;m\]\[\e[1;37m\]]\[\e[1;m\]\[\e[1;37m\]\\$\[\e[1;m\] "

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Quickly move to hard drive
alias cdhd='cd /run/media/hdd'


# BEGIN_KITTY_SHELL_INTEGRATION
#if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION

# Epic fucking penguin
echo "$(tput bold)$(date +'%A %d %B %Y')"
alias clear='~/.config/bashscripts/clear.bash'
# clear.bash hold the three lines above

# Open root rofi
alias surun='sudo rofi -show drun'


